import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from './providers';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

export const metadata: Metadata = {
  title: 'NextOptimization',
  description: 'Generated by create next app and optimized by ArtemRozzhyvin',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-black-100 min-h-screen font-poppins text-white-800'>
        <Providers>
          {children}
          <ReactQueryDevtools initialIsOpen={true} />
        </Providers>
      </body>
    </html>
  );
}
