import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

export const metadata: Metadata = {
  title: 'NextOptimization',
  description: 'Generated by create next app and optimized by ArtemRozzhyvin',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-black-100 min-h-screen font-poppins text-white-800'>{children}</body>
    </html>
  );
}
